name: setup
description: Setup the environment for tailout

inputs:
  binary_name:
    description: The name of the binary to build
    required: true
    default: "tailout"
  tailscale_oauth_client_id:
    description: The tailscale oauth client id
    required: true
  tailscale_oauth_client_secret:
    description: The tailscale oauth client secret
    required: true
  tailscale_version:
    description: The version of tailscale to use
    required: false
    default: "1.70.0"
  role_arn:
    description: The role to assume
    required: true
  region:
    description: The region to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5
      with:
        role-to-assume: ${{ inputs.role_arn }}
        role-session-name: tailout-${{ github.job }}
        aws-region: ${{ inputs.region }}
    - name: Connect runner to tailscale
      uses: tailscale/github-action@a392da0a182bba0e9613b6243ebd69529b1878aa # v4
      with:
        oauth-client-id: ${{ inputs.tailscale_oauth_client_id }}
        oauth-secret: ${{ inputs.tailscale_oauth_client_secret }}
        version: ${{ inputs.tailscale_version }}
        tags: tag:github-actions-runner
        args: --operator=runner
    - name: Download ${{ inputs.binary_name }} binary
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
      with:
        name: ${{ inputs.binary_name }}
        path: bin/
    - name: Make ${{ inputs.binary_name }} executable
      run: chmod +x bin/${{ inputs.binary_name }}
      shell: bash
    - name: Move ${{ inputs.binary_name }} to /usr/local/bin
      run: sudo mv bin/${{ inputs.binary_name }} /usr/local/bin
      shell: bash
