name: setup
description: Setup the environment for tailout

inputs:
  binary_name:
    description: The name of the binary to build
    required: true
    default: "tailout"
  tailscale_oauth_client_id:
    description: The tailscale oauth client id
    required: true
  tailscale_oauth_client_secret:
    description: The tailscale oauth client secret
    required: true
  tailscale_version:
    description: The version of tailscale to use
    required: false
    default: "1.70.0"
  role_arn:
    description: The role to assume
    required: true
  region:
    description: The region to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
      with:
        role-to-assume: ${{ inputs.role_arn }}
        role-session-name: tailout-${{ github.job }}
        aws-region: ${{ inputs.region }}
    - name: Connect runner to tailscale
      uses: tailscale/github-action@5d536117a7378beffcd6d8523ce73c50fa98684d # v3
      with:
        oauth-client-id: ${{ inputs.tailscale_oauth_client_id }}
        oauth-secret: ${{ inputs.tailscale_oauth_client_secret }}
        version: ${{ inputs.tailscale_version }}
        tags: tag:github-actions-runner
        args: --operator=runner
    - name: Download ${{ inputs.binary_name }} binary
      uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4
      with:
        name: ${{ inputs.binary_name }}
        path: bin/
    - name: Make ${{ inputs.binary_name }} executable
      run: chmod +x bin/${{ inputs.binary_name }}
      shell: bash
    - name: Move ${{ inputs.binary_name }} to /usr/local/bin
      run: sudo mv bin/${{ inputs.binary_name }} /usr/local/bin
      shell: bash
