name: setup
description: Setup the environment for xit

inputs:
  binary_path:
    description: The path of the binary to setup
    required: true
    default: "bin/xit"
  tailscale_authkey:
    description: The tailscale authkey to use
    required: true
  tailscale_version:
    description: The version of tailscale to use
    required: false
    default: "1.42.0"
  role_arn:
    description: The role to assume
    required: true
  region:
    description: The region to use
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role_arn }}
        role-session-name: xit-${{ github.job }}
        aws-region: ${{ inputs.region }}
    - name: Connect runner to tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ inputs.tailscale_authkey }}
        version: ${{ inputs.tailscale_version }}
    - name: Download ${{ inputs.binary_path }} binary
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.binary_path }}
    - name: Make ${{ inputs.binary_path }} executable
      run: chmod +x ${{ inputs.binary_path }}
      shell: bash
    - name: Move ${{ inputs.binary_path }} to /usr/local/bin
      run: sudo mv ${{ inputs.binary_path }} /usr/local/bin
      shell: bash
